#!/bin/bash

echo "════════════════════════════════════════════════════════════════"
echo "  📋 MIGRATIONS SQL SUPABASE - COPIER/COLLER"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "🔗 Ouvrez d'abord ce lien dans votre navigateur:"
echo "   https://app.supabase.com/project/lcsidczjexcfxajuoaiw/sql/new"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  MIGRATION 001 - SCHEMA (Créer les tables)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 Commande pour afficher Migration 001:"
echo "   cat supabase/migrations/001_initial_schema.sql"
echo ""
echo "▶️  Étapes:"
echo "   1. Exécutez: cat supabase/migrations/001_initial_schema.sql"
echo "   2. Copiez TOUT le contenu affiché"
echo "   3. Collez dans Supabase SQL Editor"
echo "   4. Cliquez 'Run'"
echo "   5. Attendez 'Success'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  MIGRATION 002 - RLS POLICIES (Sécurité)"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "📝 Commande pour afficher Migration 002:"
echo "   cat supabase/migrations/002_rls_policies.sql"
echo ""
echo "▶️  Étapes:"
echo "   1. Exécutez: cat supabase/migrations/002_rls_policies.sql"
echo "   2. Copiez TOUT le contenu affiché"
echo "   3. Collez dans Supabase SQL Editor (nouvelle requête)"
echo "   4. Cliquez 'Run'"
echo "   5. Attendez 'Success'"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  ✅ VÉRIFICATION"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Après les migrations, vérifiez dans Supabase → Table Editor:"
echo ""
echo "Vous devriez voir 9 tables:"
echo "  ✓ profiles"
echo "  ✓ comparison_sessions"
echo "  ✓ scoring_templates"
echo "  ✓ model_benchmarks"
echo "  ✓ files"
echo "  ✓ transactions"
echo "  ✓ roles"
echo "  ✓ groups"
echo "  ✓ group_members"
echo ""
echo "════════════════════════════════════════════════════════════════"
echo "  🚀 DÉMARRER L'APP"
echo "════════════════════════════════════════════════════════════════"
echo ""
echo "Une fois les migrations exécutées:"
echo "   npm run server"
echo ""
echo "Puis dans un autre terminal:"
echo "   cd client && npm run dev"
echo ""
echo "Ouvrir: http://localhost:3080"
echo ""
echo "════════════════════════════════════════════════════════════════"
